# Variables

In [ ]:
#BASES
booleen : bool = 0/1 = True/False
chaine de caractere : str : 'mot'
assigner une valeur : =
entier : int
decimaux : float

liste : list : []
dictionnaires : dict : {key:value}

in
not in
...

In [1]:
integer, flt = 5, 6.54 #tuples

In [2]:
lst = [4,6,8,10] #LISTES
print(lst[2])  #affiche le 3e élément de lst
print(lst[-1]) # le "-" permet de parcourir la liste en sens inverse -1 = dernier élément de la liste
lst.append(11) #Ajoute 11 à la fin de la liste
print(lst)     #Affiche la liste
element_pop = lst.pop(4) #retire l element de la liste entré en parametres
element_pop
print(lst)
lst[1] = 0     # Remplace l'element en Position 1 par 0
print(lst)

8
10
[4, 6, 8, 10, 11]
[4, 6, 8, 10]
[4, 0, 8, 10]


In [15]:
#Dictionnaires

dictionnaires se fait comme ceci :    dict = {key:value} OU pour rajouter une valeur : dct['eventuellement'] = 56

dct = {'oui': True,
       'non': 5.4}
dct['eventuellement'] = 56
print(dct)

{'oui': True, 'non': 5.4, 'eventuellement': 56}


In [17]:
#set
pour le moment ya rien frr

# CLASSES

In [27]:
#Class

#Une classe est un objet qui a des attributs qu il legera 
#à toutes les classes filles qui hériteront de ses attributs, méthodes ...etc

class Personne:
    """Classe définissant une personne caractérisée par :
    - son nom
    - son prénom
    - son âge
    - son lieu de résidence"""
    personnes_crees = 0
    
    def __init__(self, nom, prenom, age, lieu_residence):
        """Constructeur de notre classe"""
        self.nom = nom
        self.prenom = prenom
        self.age = age
        self.lieu_residence = lieu_residence
        Personne.personnes_crees += 1
    
    def get_older(self): #methode d'instance
        self.age += 1
    
    def combien(cls): #methode de classe
        print('{0} personnes ont été crées'.format(cls.personnes_crees))
    combien = classmethod(combien)
    
    def bonjour(): #methode statique
        print("bonjour")
    bonjour = staticmethod(bonjour)

Hubert = Personne("Bonnisseur Delabatte", "Hubert", 45, "Le Caire")   #Creation de la premiere classe personne
print(Hubert.age)
Hubert.get_older()
print(Hubert.age)

Personne.combien()
Personne.bonjour()

45
46
1 personnes ont été crées
bonjour


In [ ]:
#héritage
class sous_per(Personne):
    def addtional_attribute(self, oui):
        self.oui = oui

In [ ]:
#Accesseur Mutateur cf OpenClassroom
class Personne:
    """Classe définissant une personne caractérisée par :
    - son nom ;
    - son prénom ;
    - son âge ;
    - son lieu de résidence"""

    
    def __init__(self, nom, prenom):
        """Constructeur de notre classe"""
        self.nom = nom
        self.prenom = prenom
        self.age = 33
        self._lieu_residence = "Paris" # Notez le souligné _ devant le nom
    def _get_lieu_residence(self):
    """Méthode qui sera appelée quand on souhaitera accéder en lecture
        à l'attribut 'lieu_residence'"""
        
        
        print("On accède à l'attribut lieu_residence !")
        return self._lieu_residence
    def _set_lieu_residence(self, nouvelle_residence):
        """Méthode appelée quand on souhaite modifier le lieu de résidence"""
        print("Attention, il semble que {} déménage à {}.".format( \
                self.prenom, nouvelle_residence))
        self._lieu_residence = nouvelle_residence
    # On va dire à Python que notre attribut lieu_residence pointe vers une
    # propriété
    lieu_residence = property(_get_lieu_residence, _set_lieu_residence)  #si on enleve set, le lieu ne sera pas modifiable, idem pour get: on ne pourra pas y acceder

In [28]:
dir(person1) #affiche toutes les méthodes de la classe

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'age',
 'bonjour',
 'combien',
 'get_older',
 'lieu_residence',
 'nom',
 'personnes_crees',
 'prenom']

In [30]:
Hubert.__dict__

{'nom': 'Bonnisseur Delabatte',
 'prenom': 'Hubert',
 'age': 46,
 'lieu_residence': 'Le Caire'}

# CONDITIONS/BOUCLES/TRY

In [13]:
boucles : while, for
test if/else: |      &    or    and : == : !=  : > : >= : < : <=
    
#Avec comme exemples d'utilisation :

i = 1
while i < 10:
    print("itération: {}".format(str(i)))
    if i%2 == 0:
        print("paire")
    elif i%2 == 1:
        print("impair")
    else: 
        print("Jean Marie Bigard est drôle")
    i +=1   

itération: 1
impair
itération: 2
paire
itération: 3
impair
itération: 4
paire
itération: 5
impair
itération: 6
paire
itération: 7
impair
itération: 8
paire
itération: 9
impair


In [14]:
for i in range(0, 10):
    print("itération: {}".format(str(i)))
    if i%2 == 0:
        print("paire")
    elif i%2 == 1:
        print("impair")
    else:
        print("Jean Marie Bigard est drôle")

itération: 0
paire
itération: 1
impair
itération: 2
paire
itération: 3
impair
itération: 4
paire
itération: 5
impair
itération: 6
paire
itération: 7
impair
itération: 8
paire
itération: 9
impair


In [31]:
#compréhension de listes
lst = [i*11 for i in range(1,11)]
print(lst)
lst = [i*11 for i in range(1,11) if i%2 == 0]
print(lst)

[11, 22, 33, 44, 55, 66, 77, 88, 99, 110]
[22, 44, 66, 88, 110]


In [40]:
try:
    La-normalement-ça-marche-pas
    mais_vu_que_tu_as_un_try_ça_passe
except:
    print("Magie")
#On peut préciser les erreur par ex: except FileNotFound etc...

Magie


# LIBRAIRIES

# NUMPY

In [2]:
import numpy as np

In [42]:
my_list = [1,2,3]
np.array(my_list)

array([1, 2, 3])

In [43]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
oui = np.zeros(shape = (2,20))
oui

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]])

In [44]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [4]:
np.linspace(0,12,6)

array([ 0. ,  2.4,  4.8,  7.2,  9.6, 12. ])

In [47]:
np.random.rand(2) #rand = distribution uniforme entre 0 et 1 exclu

array([0.56435195, 0.48425284])

In [49]:
np.random.rand(5,5)

array([[0.89369688, 0.45647965, 0.33631362, 0.63448416, 0.37807634],
       [0.51792714, 0.62704815, 0.934366  , 0.94412647, 0.22928539],
       [0.05846204, 0.30058333, 0.43094527, 0.2730811 , 0.01122991],
       [0.17741927, 0.39386487, 0.32232717, 0.75145825, 0.87516663],
       [0.58134119, 0.52101885, 0.79627246, 0.30163392, 0.38504554]])

In [51]:
np.random.randn(5,5) #randn = loi normale

array([[-0.15624658, -0.96259182, -1.16036812, -1.21701294,  0.55647   ],
       [ 0.60921366, -0.82357013,  0.6178268 ,  0.73124755,  0.88424064],
       [ 0.0382265 , -0.20900484,  1.08083492,  0.01922942, -1.04486756],
       [ 0.76738616, -1.86128161, -0.26439617,  1.91000445, -0.67065013],
       [-0.35899453, -0.15301589,  1.10936214,  0.43022983, -0.85907555]])

In [52]:
np.random.randint(1,100)

12

In [53]:
np.random.randint(1,100, 10)

array([90, 67, 27, 51, 90, 97, 54, 69,  9, 75])

In [72]:
arr = np.random.randint(0, 100100, 25)
arr = arr.reshape(5,5)
arr

array([[29069, 39870, 59148, 28577, 97617],
       [ 1202, 35784, 79940, 23146, 37362],
       [14676,  1399, 12995, 67026, 85012],
       [ 5711, 63581, 38152, 78080, 45031],
       [79215, 65007,  6863, 84488, 74175]])

In [71]:
print(arr.max())
print(arr.argmax())
print(arr.min())
print(arr.argmin())
arr.shape

98074
6
3074
8


(5, 5)

In [79]:
arr = np.arange(0,10)
print(arr + arr)
print(arr - arr)
print(arr * arr)
print(arr / arr) #dicision par zero = Nan
print(1/arr)
print(arr**3)

[ 0  2  4  6  8 10 12 14 16 18]
[0 0 0 0 0 0 0 0 0 0]
[ 0  1  4  9 16 25 36 49 64 81]
[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.]
[       inf 1.         0.5        0.33333333 0.25       0.2
 0.16666667 0.14285714 0.125      0.11111111]
[  0   1   8  27  64 125 216 343 512 729]


C:\Users\grego\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: invalid value encountered in true_divide
  """
C:\Users\grego\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: RuntimeWarning: divide by zero encountered in true_divide
  


In [81]:
#toutes les fonctions universelles sont dispos
print(np.log(arr))
print(np.sqrt(arr))

[      -inf 0.         0.69314718 1.09861229 1.38629436 1.60943791
 1.79175947 1.94591015 2.07944154 2.19722458]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


C:\Users\grego\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  


# PANDAS

In [88]:
import pandas as pd
dataset = pd.read_csv("../Documents/titanic/train.csv") #lire un dataframe
dataset2 = pd.DataFrame(columns=['1stcol', '2ndcol'])
dataset2 = pd.DataFrame({'col1': [1, 2], 'col2': [3, 4]})
dataset2

# PANDAS : manipuler des DataFrames

['NomDeColonne'] : array
[['NomDeColonne']] : DataFrame
df.head(6) : renvoie les 6 premieres lignes du df
pd.concat(df1, df2)
df.drop(['colonne1', 'colonne2']) : retire une colonne de df
df.nomColonne.fillna(45) : remplace les nan par 45 dans la colonne du df
df.colonne.unique() : donne chq valeur de la colonne
astype() : change le type de valeur
isna() : renvoie True  pour chq nan dans la colonne
df.loc(test_Conditionnel, ...) renvoie les rows du df respectant la condition
df.iloc : prend index, renvoie la ligne du df
get_dummies : One_Hot_Encoding
    
    
https://pandas.pydata.org/pandas-docs/stable/

col1  col2
0     1     3
1     2     4

# MATPLOTLIB

In [85]:
from matplotlib import pyplot as plt
plt.plot(x, y) #droite
plt.scatter(x, y) #nuage de points
plt.bar(x, y) #histogramme
plt.pie(x, y) #camembert

#ajouter des labels
plt.xlabel("xlabel")
plt.ylabel("ylabel")


#subplots
plt.figure()
plt.scatter(x1, y1)
plt.title("GRAPH_1")
plt.figure()
plt.bar(x2, y2)
plt.title("GRAPH_2")

OU

for machin in machins:
    plt.scatter(dataset2['normalized_age'], dataset2['normalized_salary'], c = labels, s=15, cmap='gist_rainbow') #s = taille des points
    plt.show()

#A ajouter: multilines plot, legend, 3Dplots et autres

#3D
from mpl_toolkits.mplot3d import Axes3D
fig = plt.figure()
ax = plt.axes(projection='3d')

z = np.linspace(0, 1, 100)
x = z * np.sin(20 * z)
y = z * np.cos(20 * z)

c = x + y

ax.scatter(x, y, z, c=c)

# REGEX

In [106]:
import re
string = "oui, oui, oui, oui ,oui"
re.findall(r'\w+', string)
find_or_not = bool(re.match(r'oui', string))
print(find_or_not)
find_or_not = bool(re.match(r'non', string))
print(find_or_not)
re.search('oui', string)


^ : debut de chaîne
$ : fin de chaine
\. : echappement du caractere .
\d
\D
[A-Z]
[0-9]
+
*
(?=) : Lookahead
(?<=) : Lookbehind
(?!) : negative Lookahead
(?<!) : negative Lookbehind
http://regex101.com/

True
False


"<re.Match object; span=(0, 3), match='oui'>"

# SKLEARN

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn import tree
from sklearn.svm import SVC

#Pour le machine Learning

#X_train = df_train[['ValeurPredictive1', 'ValeurPredictive2', 'ValeurPredictive3']]
#X_train = pd.get_dummies(data=X_train)

#X_test = df_test[['ValeurPredictive1', 'ValeurPredictive2', 'ValeurPredictive3']] : DONNEES REELLES

#y_train = df_train[['MaValeurAPredire']]

#clf = SVC(gamma='auto')
#clf = clf.fit(X_train, y_train) 
#y_pred = clf.predict(X_test)

#clf = tree.DecisionTreeClassifier()
#clf = clf.fit(X_train, y_train)
#y_pred = clf.predict(X_test)

#logistic_regr = LogisticRegression()
#logistic_regr.fit(X_train, y_train)
#y_pred = logistic_regr.predict(X_test)

#y_pred = logistic_regr.predict(X_test)
#confusion_matr = confusion_matrix(y_test, y_pred)


#metrics.auc(x, y[, reorder])
#metrics.confusion_matrix(y_true, y_pred[, …])

# SELENIUM/ BEAUTIFULSOUP

In [ ]:
# SCRAPPING : BeautifulSoup

from bs4 import BeautifulSoup

soup = BeautifulSoup(html, 'html.parser') : prend le code HTML ici nommé html
soup.findall('h1') : prend tous le h1 du html
soup.select('div h2') prend tous les h2 de div
soup.select('div.block2 h2') : cherche les h2 dans toute les divs ayant la class block2

...



#SELENIUM

from selenium import webdriver

browser = webdriver.Firefox(executable_path = 'C:/Users/grego/Documents/geckodriver/geckodriver.exe') #geckodriver obligatoire
browser.get('path')
element = browser.find_element_by_class_name('class_name')
element2 = browser.find_element_by_xpath('xpath')
element.text
element.click()